N = ["Donovan", "Nathan", "Andres", "Jason","Alex"];
S = ["Carlos", "Cynthia", "Yve", "Chanel","Jennifer"];
case1 = union(N,S);
case2 = intersect(N,S);
case3 = setdiff(N,S);
case4 = setdiff(S,N);
display(case1);
display(case2);
display(case3);
display(case4);